name: BlockyKingdom
main: at.jojokobi.blockykingdom.BlockyKingdomPlugin
version: 0.1
author: jojokobi
load: STARTUP
depend: [JojokobiUtil, JojosGenerator]
api-version: 1.19
commands:
  resetstats:
    description: Resets a players skills
    usage: /resetstats
  glowvillagers:
    description: Makes all villagers of the current kingdom glow for 15 minutes
    usage: /glowvillagers