name: BlockyKingdom
main: at.jojokobi.blockykingdom.BlockyKingdomPlugin
version: 0.1
author: jojokobi
load: STARTUP
depend: [JojokobiUtil, JojosGenerator]
api-version: 1.17
commands:
  resetstats:
    description: Resets a players skills
    usage: /resetstats